### ISSUE TITLE
Overførsel af ansættelsesdata fra Signatur til SBSYS (85.11.00-P20-28-23)

### ISSUE THREAD

**Issue by cbh-randers** [Randers-Kommune-Digitalisering/intern-udvikling#7]
Personale og HR har tidligere haft en robot, som sikrede at ansættelsesdokumenter eks. CV blev automatisk overført fra signatur til personalemapper i sbsys. De ønsker at få en lignede robot tilbage. 

```[tasklist]
### Tasks
- [ ] https://github.com/Randers-Kommune-Digitalisering/doc-arbejdsgangsbeskrivelser/issues/74
- [ ] Test journalisering af pdf til personalesag og overvåg i SD applikation.
- [ ] https://github.com/Randers-Kommune-Digitalisering/doc-arbejdsgangsbeskrivelser/issues/92
```
